### PR TITLE
Remove some unused endpoints

### PR DESCRIPTION
**Pull request by akihikokuroda**
### Summary
This PR removes some api endpoints that are not used.

### CODE REVIEW

**Comment by akihikokuroda** [comment]
@psschwei `/metrics`  endpoint is exposing system information and statistics.  I'm not sure what we should do with it.  WDYT Thanks!

**Comment by psschwei** [comment]
> @psschwei `/metrics` endpoint is exposing system information and statistics. I'm not sure what we should do with it. WDYT Thanks!

Those metrics are picked up by Sysdig and Grafana (or at least will be, if we ever get a Granfana instance), so we'll need them exposed for monitoring.

It might be worth checking with Runtime to see how they handle this type of situation (if there's any kind of common pattern on exposing metrics we should piggyback off of that rather than trying to roll our own).

**Comment by Tansito** [comment]
After some internal discussions let's keep the end-point 👍

**Review by Tansito — COMMENTED** [review]
Personally I would just remove the `else` statement:

```py
urlpatterns = [
        path("readiness/", probes.views.readiness, name="readiness"),
        path("liveness/", probes.views.liveness, name="liveness"),
        path("version/", version.views.version, name="version"),
        path("", include("django_prometheus.urls")),
        re_path(r"^api/v1/", include(("api.v1.urls", "api"), namespace="v1")),
        path(
            "DomainVerification.html",
            TemplateView.as_view(template_name="DomainVerification.html"),
        ),
    ]
    
if settings.DEBUG:
    urlpatterns += re_path(
            r"^swagger(?P<format>\.json|\.yaml)$",
            schema.without_ui(cache_timeout=0),
            name="schema-json",
        )
    urlpatterns += re_path(
            r"^swagger/$",
            schema.with_ui("swagger", cache_timeout=0),
            name="schema-swagger-ui",
        )
    urlpatterns += re_path(
            r"^redoc/$", schema.with_ui("redoc", cache_timeout=0), name="schema-redoc"
        )
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
```

**Comment by akihikokuroda** [comment]
@Tansito Yes, I agree :-)

**Comment by akihikokuroda** [comment]
@Tansito It didn't work.  `re_path` can not b used like `static`.

**Comment by Tansito** [comment]
@akihikokuroda checks passed did you fix it or...?

**Comment by akihikokuroda** [comment]
@Tansito It didn't work so I took out the last change.

**Review by Tansito — APPROVED** [review]
Ooooh, I see. I would then jus add `static` end-points to the array like the others. Apart from it I suppose we can go by now with this solution 👍 

Thanks @akihikokuroda to take a look

**Pull request merged**
